# Site settings
title: Friday
description: A blog about Spijoker
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Spijoker
user_description: Still Nothing but a student
user_title: Software student
email: spijoker@outlook.com
twitter_username: Jayson Shawn @Spijoke
github_username:  Spijoker
gplus_username:  ∞

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
